### ISSUE TITLE
Appium Crosswalk

### ISSUE THREAD

**Issue by dioxmio** [tony--/cordova-plugin-crosswalk-webview-xwalk-5133#1]
Hi, 

it is not working for me when using Appium. Any idea how I could make it work without changing the driver? Any help would be appreciated :)

**Comment by tony--** [comment]
Hi @dioxmio - Did you mean to log this on [the main cordova-plugin-crosswalk-webview repo](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview)?
